columns:
  - duration                    :   int64  
  - protocol_type               :   object 
  - service                     :   object 
  - flag                        :   object 
  - src_bytes                   :   int64  
  - dst_bytes                   :   int64  
  - land                        :   int64  
  - wrong_fragment              :   int64  
  - urgent                      :   int64  
  - hot                         :   int64  
  - num_failed_logins           :   int64  
  - logged_in                   :   int64  
  - num_compromised             :   int64  
  - root_shell                  :   int64  
  - su_attempted                :   int64  
  - num_root                    :   int64  
  - num_file_creations          :   int64  
  - num_shells                  :   int64  
  - num_access_files            :   int64  
  - num_outbound_cmds           :   int64  
  - is_host_login               :   int64  
  - is_guest_login              :   int64  
  - count                       :   int64  
  - srv_count                   :   int64  
  - serror_rate                 :   float64
  - srv_serror_rate             :   float64
  - rerror_rate                 :   float64
  - srv_rerror_rate             :   float64
  - same_srv_rate               :   float64
  - diff_srv_rate               :   float64
  - srv_diff_host_rate          :   float64
  - dst_host_count              :   int64  
  - dst_host_srv_count          :   int64  
  - dst_host_same_srv_rate      :   float64
  - dst_host_diff_srv_rate      :   float64
  - dst_host_same_src_port_rate :   float64
  - dst_host_srv_diff_host_rate :   float64
  - dst_host_serror_rate        :   float64
  - dst_host_srv_serror_rate    :   float64
  - dst_host_rerror_rate        :   float64
  - dst_host_srv_rerror_rate    :   float64
  - attack                      :   object 
  - level                       :   int64 

numerical_columns:
  - duration
  - src_bytes
  - dst_bytes
  - land
  - wrong_fragment
  - urgent
  - hot
  - num_failed_logins
  - logged_in
  - num_compromised
  - root_shell
  - su_attempted
  - num_root
  - num_file_creations
  - num_shells
  - num_access_files
  - num_outbound_cmds
  - is_host_login
  - is_guest_login
  - count
  - srv_count
  - serror_rate
  - srv_serror_rate
  - rerror_rate
  - srv_rerror_rate
  - same_srv_rate
  - diff_srv_rate
  - srv_diff_host_rate
  - dst_host_count
  - dst_host_srv_count
  - dst_host_same_srv_rate
  - dst_host_diff_srv_rate
  - dst_host_same_src_port_rate
  - dst_host_srv_diff_host_rate
  - dst_host_serror_rate
  - dst_host_srv_serror_rate
  - dst_host_rerror_rate
  - dst_host_srv_rerror_rate
  - level

categorical_columns:
  - protocol_type
  - service
  - flag
  - attack